/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  collections: {
    restaurants: Restaurant;
    orders: Order;
    dishes: Dish;
    cities: City;
    users: User;
    customers: Customer;
    media: Media;
    categories: Category;
    FeedbackAndCooperations: FeedbackAndCooperation;
    'delivery-origins': DeliveryOrigin;
    'distance-tiers': DistanceTier;
    'shipping-providers': ShippingProvider;
    'shipping-quotes': ShippingQuote;
    'shipping-bookings': ShippingBooking;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    dishes: DishesSelect<false> | DishesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    FeedbackAndCooperations: FeedbackAndCooperationsSelect<false> | FeedbackAndCooperationsSelect<true>;
    'delivery-origins': DeliveryOriginsSelect<false> | DeliveryOriginsSelect<true>;
    'distance-tiers': DistanceTiersSelect<false> | DistanceTiersSelect<true>;
    'shipping-providers': ShippingProvidersSelect<false> | ShippingProvidersSelect<true>;
    'shipping-quotes': ShippingQuotesSelect<false> | ShippingQuotesSelect<true>;
    'shipping-bookings': ShippingBookingsSelect<false> | ShippingBookingsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: string;
  title: string;
  description?: string | null;
  address: string;
  deliveryTime: '30' | '45' | '60' | '90' | '120';
  deliveryPrice: number;
  freeAfterAmount?: number | null;
  enabledShippingProviders?: (string | ShippingProvider)[] | null;
  workingHours: {
    openTime:
      | '0700'
      | '0730'
      | '0800'
      | '0830'
      | '0900'
      | '0930'
      | '1000'
      | '1030'
      | '1100'
      | '1130'
      | '1200'
      | '1230'
      | '1300'
      | '1330'
      | '1400'
      | '1430'
      | '1500'
      | '1530'
      | '1600'
      | '1630'
      | '1700'
      | '1730'
      | '1800';
    closeTime: '1900' | '1930' | '2000' | '2030' | '2100' | '2130' | '2200' | '2230' | '2300' | '2330' | '2400';
  };
  is24h?: boolean | null;
  isClosed?: boolean | null;
  isDelivery: boolean;
  selfPickupEnabled?: boolean | null;
  slug?: string | null;
  brandColor?: string | null;
  logoImage?: (string | null) | Media;
  appIcon?: (string | null) | Media;
  brandedEnabled?: boolean | null;
  bannerImage?: (string | null) | Media;
  categories?: (string | Category)[] | null;
  dishes?: (string | Dish)[] | null;
  budgetCategory?: ('1' | '2' | '3') | null;
  isBlocked?: boolean | null;
  relatedToUser?: (string | null) | Customer;
  cities?: (string | City)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-providers".
 */
export interface ShippingProvider {
  id: string;
  restaurantId: string | Restaurant;
  providerType: 'distance' | 'manual' | 'baemin' | 'coupang' | 'yogiyo';
  isEnabled?: boolean | null;
  priority: number;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  createdBy?: (string | null) | Customer;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name?: string | null;
  phone?: string | null;
  restaurant?: (string | Restaurant)[] | null;
  isBlocked?: boolean | null;
  roles?: ('admin' | 'author' | 'guest')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  category: string;
  value: string;
  order?: number | null;
  type: 'dish' | 'restaurant';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes".
 */
export interface Dish {
  id: string;
  title: string;
  description: string;
  price: number;
  gram: number;
  availableAmount?: number | null;
  cookTime: number;
  categories?: (string | null) | Category;
  image?: (string | null) | Media;
  restaurant: string | Restaurant;
  createdBy?: (string | null) | Customer;
  isBlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  title?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  city?: string | null;
  district: string;
  apartment: string;
  houseNumber: string;
  entrance?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  fullAddress?: string | null;
  phoneNumber: number;
  orderStatus?: ('pending' | 'recieved' | 'sended' | 'delivered' | 'rejected') | null;
  totalAmount?: number | null;
  deliveryPrice?: string | null;
  shippingQuoteId?: string | null;
  shippingProvider?: string | null;
  shippingBookingId?: string | null;
  shippingStatus?:
    | (
        | 'pending'
        | 'quoted'
        | 'pending_manual'
        | 'awaiting_customer_response'
        | 'confirmed'
        | 'cancelled_timeout'
        | 'cancelled_by_customer'
        | 'in_progress'
        | 'delivered'
      )
    | null;
  scheduledDeliveryTime?: string | null;
  deliveryOriginId?: string | null;
  restaurantName?: string | null;
  commentToCourier?: string | null;
  commentToRestaurant?: string | null;
  isDelivery: boolean;
  dishes?:
    | {
        dish?: (string | null) | Dish;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  restaurantID: string;
  orderedByUser: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone: string;
  addresses?:
    | {
        city?: string | null;
        district: string;
        apartment: string;
        houseNumber: string;
        entrance?: string | null;
        alias?: string | null;
        isDefault?: boolean | null;
        fullAddress?: string | null;
        roadAddress?: string | null;
        jibunAddress?: string | null;
        zonecode?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        buildingName?: string | null;
        addressDetail?: string | null;
        id?: string | null;
      }[]
    | null;
  roles?: 'user'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeedbackAndCooperations".
 */
export interface FeedbackAndCooperation {
  id: string;
  name?: string | null;
  phoneNumber?: string | null;
  description: string;
  type: 'cooperation' | 'feedback';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-origins".
 */
export interface DeliveryOrigin {
  id: string;
  restaurantId: string | Restaurant;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  operatingHours?:
    | {
        day: number;
        open: string;
        close: string;
        id?: string | null;
      }[]
    | null;
  maxCapacity: number;
  currentLoad?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distance-tiers".
 */
export interface DistanceTier {
  id: string;
  restaurantId: string | Restaurant;
  minDistanceKm: number;
  maxDistanceKm: number;
  price: number;
  estimatedMinutes: number;
  freeAfterAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-quotes".
 */
export interface ShippingQuote {
  id: string;
  quoteId: string;
  providerId: string;
  providerName: string;
  providerType?: ('distance' | 'manual' | 'external') | null;
  price: number;
  estimatedMinutes?: number | null;
  validUntil: string;
  restaurantId: string;
  customerId: string;
  request?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-bookings".
 */
export interface ShippingBooking {
  id: string;
  bookingId: string;
  quoteId: string;
  orderId: string | Order;
  providerId: string;
  status: 'pending' | 'confirmed' | 'in_progress' | 'delivered' | 'cancelled';
  trackingUrl?: string | null;
  externalBookingId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'restaurants';
        value: string | Restaurant;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'dishes';
        value: string | Dish;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'FeedbackAndCooperations';
        value: string | FeedbackAndCooperation;
      } | null)
    | ({
        relationTo: 'delivery-origins';
        value: string | DeliveryOrigin;
      } | null)
    | ({
        relationTo: 'distance-tiers';
        value: string | DistanceTier;
      } | null)
    | ({
        relationTo: 'shipping-providers';
        value: string | ShippingProvider;
      } | null)
    | ({
        relationTo: 'shipping-quotes';
        value: string | ShippingQuote;
      } | null)
    | ({
        relationTo: 'shipping-bookings';
        value: string | ShippingBooking;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  address?: T;
  deliveryTime?: T;
  deliveryPrice?: T;
  freeAfterAmount?: T;
  enabledShippingProviders?: T;
  workingHours?:
    | T
    | {
        openTime?: T;
        closeTime?: T;
      };
  is24h?: T;
  isClosed?: T;
  isDelivery?: T;
  selfPickupEnabled?: T;
  slug?: T;
  brandColor?: T;
  logoImage?: T;
  appIcon?: T;
  brandedEnabled?: T;
  bannerImage?: T;
  categories?: T;
  dishes?: T;
  budgetCategory?: T;
  isBlocked?: T;
  relatedToUser?: T;
  cities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  city?: T;
  district?: T;
  apartment?: T;
  houseNumber?: T;
  entrance?: T;
  latitude?: T;
  longitude?: T;
  fullAddress?: T;
  phoneNumber?: T;
  orderStatus?: T;
  totalAmount?: T;
  deliveryPrice?: T;
  shippingQuoteId?: T;
  shippingProvider?: T;
  shippingBookingId?: T;
  shippingStatus?: T;
  scheduledDeliveryTime?: T;
  deliveryOriginId?: T;
  restaurantName?: T;
  commentToCourier?: T;
  commentToRestaurant?: T;
  isDelivery?: T;
  dishes?:
    | T
    | {
        dish?: T;
        quantity?: T;
        id?: T;
      };
  restaurantID?: T;
  orderedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes_select".
 */
export interface DishesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  gram?: T;
  availableAmount?: T;
  cookTime?: T;
  categories?: T;
  image?: T;
  restaurant?: T;
  createdBy?: T;
  isBlocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  title?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  addresses?:
    | T
    | {
        city?: T;
        district?: T;
        apartment?: T;
        houseNumber?: T;
        entrance?: T;
        alias?: T;
        isDefault?: T;
        fullAddress?: T;
        roadAddress?: T;
        jibunAddress?: T;
        zonecode?: T;
        latitude?: T;
        longitude?: T;
        buildingName?: T;
        addressDetail?: T;
        id?: T;
      };
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  restaurant?: T;
  isBlocked?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  category?: T;
  value?: T;
  order?: T;
  type?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeedbackAndCooperations_select".
 */
export interface FeedbackAndCooperationsSelect<T extends boolean = true> {
  name?: T;
  phoneNumber?: T;
  description?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-origins_select".
 */
export interface DeliveryOriginsSelect<T extends boolean = true> {
  restaurantId?: T;
  name?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  operatingHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  maxCapacity?: T;
  currentLoad?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distance-tiers_select".
 */
export interface DistanceTiersSelect<T extends boolean = true> {
  restaurantId?: T;
  minDistanceKm?: T;
  maxDistanceKm?: T;
  price?: T;
  estimatedMinutes?: T;
  freeAfterAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-providers_select".
 */
export interface ShippingProvidersSelect<T extends boolean = true> {
  restaurantId?: T;
  providerType?: T;
  isEnabled?: T;
  priority?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-quotes_select".
 */
export interface ShippingQuotesSelect<T extends boolean = true> {
  quoteId?: T;
  providerId?: T;
  providerName?: T;
  providerType?: T;
  price?: T;
  estimatedMinutes?: T;
  validUntil?: T;
  restaurantId?: T;
  customerId?: T;
  request?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-bookings_select".
 */
export interface ShippingBookingsSelect<T extends boolean = true> {
  bookingId?: T;
  quoteId?: T;
  orderId?: T;
  providerId?: T;
  status?: T;
  trackingUrl?: T;
  externalBookingId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}